### ISSUE TITLE
signup: if browser is blocking popups, unable to submit

### ISSUE THREAD

**Issue by bradwbradw** [citrtech/djland#14]
this happens for both pop-up blocking extensions and Chrome's built in pop-up blocking option

not a problem if in station (since we can whitelist the domain), but could be problematic if people sign up from home

**Comment by EvanFriday** [comment]
Possible solution:

Custom CSS "alert" window slides in as an overlay instead of an actual alert.

**Comment by EvanFriday** [comment]
Duplicate Issue. Will remove popups and use message pane at top to give user feedback.
