### ISSUE TITLE
vendor/autoload.php is missing

### ISSUE THREAD

**Issue by PritamBiswas489** [citrtech/djland#217]
I have to run api2/composer.json for create vendor autoload.php
using this composer software
http://getcomposer.org/doc/01-basic-usage.md ?Thanks wait for your reply.

**Comment by scottpidzarko** [comment]
Hi Pritam,

You have to use composer to generate this file:

From our internal documentation:

Clone the DJLand Repository to a folder (suggest C:\Users\<username>\Documents\git\)

Enable mod_rewrite module
Windows: Uncomment the LoadModule mod_rewrite line in httpd.conf
Linux: sudo a2enmod rewrite

You will need artisan, as the API (currently api2) uses laravel. First install composer

(full instructions at https://getcomposer.org/doc/00-intro.md)

Windows: 
https://getcomposer.org/Composer-Setup.exe
Linux:
http://tecadmin.net/install-laravel-framework-on-ubuntu/
$ curl -sS https://getcomposer.org/installer | php
$ sudo mv composer.phar /usr/local/bin/composer
$ sudo chmod +x /usr/local/bin/composer
once composer is installed, go to djland/api2 and type:
“composer install” on the command line

Then create your ENV file in this directory from the template, filling in necessary database values

You will then need to make a unique key:
run "php artisan key:generate" on the command line

Add:
127.0.0.1 djland
127.0.0.1 citr
127.0.0.1 player
 to the bottom of your hosts file (windows only)
C:/Windows/System32/drivers/etc/
Copy it to desktop, edit it, and paste it back.

Now to edit your virtual hosts in Apache
C:\xampp\apache\conf\extra\httpd-vhosts.conf

Here is an example of a vhost entry for DJLand
<VirtualHost djland:80>
    ServerAdmin tech@dummy-host2.example.com
    DocumentRoot "C:/Users/techserv/Documents/git/djland"
    ServerName djland
    ErrorLog "logs/djland.log"
    CustomLog "logs/djland.log" common

    <Directory "C:/Users/techserv/Documents/git/djland">
      AllowOverride All
      Options None
      Require all granted
    </Directory>
</VirtualHost>
Now, copy the sample config in the root directory and configure it to point to your database.
