### ISSUE TITLE
Save Draft button disappears when an error occurs and it tells you to "Save a draft instead"

### ISSUE THREAD

**Issue by EvanFriday** [citrtech/djland#46]
What a troll of a page.

**Comment by bradwbradw** [comment]
I may have time to look at or fix some of these.  What branch is this on?

**Comment by citrtech** [comment]
The podcast branch.

On Saturday, August 22, 2015, bradwbradw <notifications@github.com> wrote:

> I may have time to look at or fix some of these. What branch is this on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citrtech/djland/issues/46#issuecomment-133714861>.
>


-- 


*---Scott Pidzarko*
Technical Services
CiTR 101.9 FM @ CiTR.ca <http://citr.ca>
(604) 363-5190

**Comment by EvanFriday** [comment]
Does not occur anymore
