### ISSUE TITLE
Searching for members doesn't default to or even have option for searching all years

### ISSUE THREAD

**Issue by scottpidzarko** [citrtech/djland#55]
When searching for members, you have to explicitly clarify which year's membership you're searching in. Annoying when trying to find people and you're not sure which years they had membership, or if the member hasn't renewed.

**Comment by EvanFriday** [comment]
Can add back in 'don't filter by year' and make back end accommodate. 

It just made queries somewhat unwieldy. Easy to add back.

**Comment by citrtech** [comment]
Great
.



*---Scott Pidzarko*
Technical Services
CiTR 101.9 FM @ CiTR.ca <http://citr.ca>
(604) 363-5190

**Comment by EvanFriday** [comment]
Issue Already Exists
