### ISSUE TITLE
Multiple Members exist with the same name, but different information (ie. phone number)

### ISSUE THREAD

**Issue by scottpidzarko** [citrtech/djland#56]
As an example, search for Eleanor in membership - there's two profiles. Not sure if this was caused by her submitting herself twice with different phone numbers, or if she changed her phone number and it duplicated.

**Comment by scottpidzarko** [comment]
There's two profiles because one is the president profile - do we delete multiple profiles/accounts like this? Do we have another class of membership for student exec?

**Comment by EvanFriday** [comment]
Student Exec Accounts shouldn't exist. They should be the individual user accounts as we now have permission levels to accommodate what we need.

Double check w/ hugo.

**Comment by citrtech** [comment]
Talked with Hugo, and he agrees - there shouldn't be an account attached to
a position, just ones attached to a person.

The exception would be the intern account, techserv, test user accounts,
and accounts associated with special podcasts - would we need a "CiTR"
account to own the special broadcasts podcast channel?



*---Scott Pidzarko*
Technical Services
CiTR 101.9 FM @ CiTR.ca <http://citr.ca>
(604) 363-5190
