### ISSUE TITLE
All podcasts say inactive even if they are inactive

### ISSUE THREAD

**Issue by EvanFriday** [citrtech/djland#58]
Podcasts page listing.

**Comment by scottpidzarko** [comment]
I can see in the database that all podcasts have "0" for their active field, but I can't see on the podcast page where there would be the indication that they are active or not.

**Comment by EvanFriday** [comment]
Steps to reproduce. Go to "podcasts" menu item. Select a podcast channel. Each episode declared inactive.

Most likely due to migration scripts not being run on that machine. Database level issue.
