### ISSUE TITLE
On library.php, the link at the bottom that links to tools/dupenuker.php is broke

### ISSUE THREAD

**Issue by scottpidzarko** [citrtech/djland#60]
Is this an outdated link we don't want anymore?

**Comment by bradwbradw** [comment]
I would suggest you just delete, or comment out the link for monday.  This tool is only for music dept staff to use maybe only once ever, really (i don't know if anybody has used it or not)

it has the potential to delete stuff from the library, so you might not want people checking that page out at the programmers meeting

**Comment by EvanFriday** [comment]
The file was moved. Add tools to url path

Evan

---- bradwbradw wrote ----

I would suggest you just delete, or comment out the link for monday.  This tool is only for music dept staff to use maybe only once ever, really (i don't know if anybody has used it or not)

it has the potential to delete stuff from the library, so you might not want people checking that page out at the programmers meeting

---

**Comment by EvanFriday** [comment]
Moved back to root, as menu does not support non-root pages. Also fixed file.
